Change localhost to 0.0.0.0 so it doesnt complain
When i use this file with default localhost and start the service, libreddit panics and gives this error
`May 04 13:56:14 vern.cc libreddit[104899]: thread 'main' panicked at 'Cannot parse localhost:2501 as address (example format: 0.0.0.0:8080)', /home/libreddit/.cargo/registry/src/github.com-1ecc6299db9ec823/libred>`
using 0.0.0.0 instead fixed it for me